# limmat config for limmat itself

num_worktrees = 4

[[tests]]
name = "fmt"
command = "cargo fmt --check"

[[tests]]
name = "build"
# Agh dunno if this is enough coverage.
# Ideally just want 'cargo check' with https://github.com/rust-lang/cargo/issues/8424
command = "cargo rustc --target-dir $LIMMAT_ORIGIN/target -- -D warnings"
cache = "by_tree"

[[tests]]
name = "test"
command = "cargo test --target-dir $LIMMAT_ORIGIN/target"
cache = "by_tree"

[[tests]]
name = "clippy"
command = "cargo clippy --all-targets -- -D warnings"
cache = "by_tree"