# cargo-vet config file. This project is not actually run by an "organisation" and doesn't have
# a serious supply chain security story, I was just curious about how cargo-vet works and to see
# what kind of audit coverage I'd get by importing some audit sources. (Answer:
# damn, that's a lotta excemptions).

[cargo-vet]
version = "0.10"

[policy.limmat]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.adler2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.ansi-control-codes]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.93"
criteria = "safe-to-deploy"

[[exemptions.async-condvar-fair]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.async-stream]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.async-stream-impl]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.83"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.7.7"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.cfg_aliases]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.20"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.20"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.18"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.colored]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.13"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.20"
criteria = "safe-to-deploy"

[[exemptions.crossterm]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.crossterm_winapi]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.directories]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.dyn-clone]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.env_filter]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.11.5"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.filetime]]
version = "0.2.25"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.fsevent-sys]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.googletest]]
version = "0.12.0"
criteria = "safe-to-run"

[[exemptions.googletest_macro]]
version = "0.12.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.http-range-header]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.9.5"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.indoc]]
version = "2.0.5"
criteria = "safe-to-deploy"

[[exemptions.inotify]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.inotify-sys]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.kqueue]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.kqueue-sys]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.162"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.limmat]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.22"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.matchit]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.mime_guess]]
version = "2.0.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.notify]]
version = "6.1.1"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-run"

[[exemptions.object]]
version = "0.36.5"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.2"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.89"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.37"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.39"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.214"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.214"
criteria = "safe-to-deploy"

[[exemptions.serde_derive_internals]]
version = "0.29.1"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.132"
criteria = "safe-to-deploy"

[[exemptions.serde_path_to_error]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.8"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-run"

[[exemptions.signal-hook]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-mio]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.strip-ansi-escapes]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.87"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.14.0"
criteria = "safe-to-deploy"

[[exemptions.test-case]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.test-case-core]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.test-case-macros]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.test-log]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.test-log-macros]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.test_bin]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.68"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.68"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.8"
criteria = "safe-to-run"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.41.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-tungstenite]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.12"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.8.19"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.8"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.22.22"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.tracing-subscriber]]
version = "0.3.18"
criteria = "safe-to-run"

[[exemptions.tungstenite]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicase]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.utf-8]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.vte]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.vte_generate_state_changes]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.6.20"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"
