name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Configure git
      run: git config --global user.email "grundbert@example.com"; git config --global user.name "Grundbert Schnlörber"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # https://github.com/actions/runner/issues/241#issuecomment-577360161
      run: script -e -c "cargo test --verbose"
